# This is a basic workflow to help you get started with Actions
name: Cron job running every 10 minutes to get Dulles arrivals
#on: push

# Controls when the workflow will run
on:
  #  # Triggers on every push
  push:
  #  # Triggers the workflow every 30 minutes
  schedule:
  - cron: "*/11 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout dullesArrivals repository
      uses: actions/checkout@v4 # checkout the repository content to github runner.
      with:
        repository: shekarpathi/dullesArrivals
        persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        clean: true

    - name: setup python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed

    - name: install python pip packages
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Configure git user name and list files
      run: |
        git config --global user.name "Shekar"
        git config --global user.email "shekar@yahoo.com"
        ls -ltra ./
        git status
        git fetch origin
        
    - name: Run script to get data for IAD arrivals
      run: |
        python getDullesArrivals.py

    - name: Add, commit and push changes
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: '.'
        push: true
        tag: 'v1.0.0 --force'
        tag_push: '--force'
        message: 'Added Dulles arrivals html'
